local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.showmode = false
opt.cmdheight = 1
opt.splitbelow = true
opt.splitright = true
opt.wrap = false
opt.scrolloff = 999
opt.virtualedit = "block"
opt.mouse = "a"
opt.clipboard = "unnamedplus"
opt.undofile = true
opt.swapfile = false
opt.updatetime = 250
opt.timeoutlen = 300
opt.ignorecase = true
opt.smartcase = true
opt.inccommand = "split"
opt.signcolumn = "yes"
opt.completeopt = "menuone,noselect"
opt.termguicolors = true

vim.g.netrw_banner = 0
vim.g.loaded_node_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_python3_provider = 0
vim.g.loaded_ruby_provider = 0
